language: node_js
node_js:
- node
- 8
- 6
- 4
cache: yarn
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  email: false
deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: vitarn/serverless-qcloud-scf
    node: node
