language: node_js
node_js:
  - node
  - 8
  - 6
  # Jest takes advantage of new features added to Node 6.
  # https://facebook.github.io/jest/docs/en/troubleshooting.html#compatibility-issues

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache: yarn

before_install:
  - which npx || yarn global add npx

script:
  - yarn coverage

after_success:
  - npx codecov

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      script: skip
      after_success: echo Ready deploy...
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true
          repo: vitarn/serverless-qcloud-scf
          node: node

notifications:
  email: false
